FROM microsoft/dotnet-framework

LABEL maintainer "John Goyette"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# VC 2010 SP1 x64
ADD https://download.microsoft.com/download/A/8/0/A80747C3-41BD-45DF-B505-E9710D2744E0/vcredist_x64.exe /vcredist_x64.exe
RUN C:\vcredist_x64.exe /quiet /install
RUN rm C:\vcredist_x64.exe

# VC 2013 x64
ADD http://download.microsoft.com/download/0/5/6/056dcda9-d667-4e27-8001-8a0c6971d6b1/vcredist_x64.exe  /vcredist_x64.exe
RUN C:\vcredist_x64.exe /quiet /install
RUN rm C:\vcredist_x64.exe

# VC 2015 x64
ADD https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe  /vcredist_x64.exe
RUN C:\vcredist_x64.exe /quiet /install
RUN rm C:\vcredist_x64.exe

# MSXML 4.0 SP3 x64
ADD https://download.microsoft.com/download/A/7/6/A7611FFC-4F68-4FB1-A931-95882EC013FC/msxml4-KB2758694-enu.exe /msxml4-KB2758694-enu.exe
RUN C:\msxml4-KB2758694-enu.exe /quiet
RUN rm C:\msxml4-KB2758694-enu.exe

# Copy binaries
COPY ./Export /SIDEXIS4
WORKDIR /SIDEXIS4

# start the service
CMD .\SidexisRestService.ConsoleHost.exe
