# escape=`

FROM microsoft/windowsservercore:1709
LABEL maintainer "John Goyette"

# Install all of our dependencies

# Install .NET Fx 3.5
RUN powershell -Command `
        $ErrorActionPreference = 'Stop'; `
        $ProgressPreference = 'SilentlyContinue'; `
        Invoke-WebRequest `
            -UseBasicParsing `
            -Uri "https://dotnetbinaries.blob.core.windows.net/dockerassets/microsoft-windows-netfx3-1709.zip" `
            -OutFile microsoft-windows-netfx3.zip; `
        Expand-Archive microsoft-windows-netfx3.zip; `
        Remove-Item -Force microsoft-windows-netfx3.zip; `
        Add-WindowsPackage -Online -PackagePath .\microsoft-windows-netfx3\microsoft-windows-netfx3-ondemand-package.cab; `
        Remove-Item -Force -Recurse microsoft-windows-netfx3

# Apply latest patch
RUN powershell -Command `
        $ErrorActionPreference = 'Stop'; `
        $ProgressPreference = 'SilentlyContinue'; `
        Invoke-WebRequest `
            -UseBasicParsing `
            -Uri "http://download.windowsupdate.com/c/msdownload/update/software/secu/2018/04/windows10.0-kb4093112-x64_08237e229b9c1de3e8878674f5815ca2746c6a2a.msu" `
            -OutFile patch.msu; `
        New-Item -Type Directory patch; `
        Start-Process expand -ArgumentList 'patch.msu', 'patch', '-F:*' -NoNewWindow -Wait; `
        Remove-Item -Force patch.msu; `
        Add-WindowsPackage -Online -PackagePath C:\patch\Windows10.0-KB4093112-x64.cab; `
        Remove-Item -Force -Recurse \patch

# default shell
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# VC 2010 SP1 x64
ADD https://download.microsoft.com/download/A/8/0/A80747C3-41BD-45DF-B505-E9710D2744E0/vcredist_x64.exe /vcredist_x64.exe
RUN /vcredist_x64.exe /quiet /install | Out-Null; rm /vcredist_x64.exe

# VC 2010 SP1 x86
ADD https://download.microsoft.com/download/C/6/D/C6D0FD4E-9E53-4897-9B91-836EBA2AACD3/vcredist_x86.exe /vcredist_x86.exe
RUN /vcredist_x86.exe /quiet /install | Out-Null; rm /vcredist_x86.exe

# VC 2013 x64
ADD http://download.microsoft.com/download/0/5/6/056dcda9-d667-4e27-8001-8a0c6971d6b1/vcredist_x64.exe /vcredist_x64.exe
RUN /vcredist_x64.exe /quiet /install | Out-Null; rm /vcredist_x64.exe

# VC 2013 x86
ADD http://download.microsoft.com/download/0/5/6/056dcda9-d667-4e27-8001-8a0c6971d6b1/vcredist_x86.exe /vcredist_x86.exe
RUN /vcredist_x86.exe /quiet /install | Out-Null; rm /vcredist_x86.exe

# VC 2015 x64
ADD https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe /vcredist_x64.exe
RUN /vcredist_x64.exe /quiet /install | Out-Null; rm /vcredist_x64.exe

# VC 2015 x86
ADD https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe /vcredist_x86.exe
RUN /vcredist_x86.exe /quiet /install | Out-Null; rm /vcredist_x86.exe

# MSXML 4.0 SP3 x64
ADD https://download.microsoft.com/download/A/7/6/A7611FFC-4F68-4FB1-A931-95882EC013FC/msxml4-KB2758694-enu.exe /msxml4-KB2758694-enu.exe
RUN /msxml4-KB2758694-enu.exe /quiet | Out-Null; rm /msxml4-KB2758694-enu.exe

# Copy binaries
COPY ./Export /SIDEXIS4
WORKDIR /SIDEXIS4

EXPOSE 42927 42928 42929

# start the service
CMD .\SidexisRestService.ConsoleHost.exe
